export const AUTH_API_END_POINT = "https://jobportal-springboot-backend-production.up.railway.app/api/v1/auth"
export const USER_API_END_POINT = "https://jobportal-springboot-backend-production.up.railway.app/api/v1/user"
export const JOB_API_END_POINT = "https://jobportal-springboot-backend-production.up.railway.app/api/v1/job"
export const APPLICATION_API_END_POINT = "https://jobportal-springboot-backend-production.up.railway.app/api/v1/application"
export const COMPANY_API_END_POINT = "https://jobportal-springboot-backend-production.up.railway.app/api/v1/admin/company"
export const ADMIN_API_END_POINT = "https://jobportal-springboot-backend-production.up.railway.app/ap1/v1/admin" 